# Generated by Django 5.1 on 2024-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menyu',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menyu',
            name='photo',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
