# Generated by Django 4.2 on 2024-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_menyu_des_food_photo_alter_food_small_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi(kichik)'),
        ),
    ]
