# Generated by Django 4.2 on 2024-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_food_small_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('author_id', models.DecimalField(decimal_places=0, max_digits=9)),
                ('text', models.TextField()),
            ],
        ),
    ]
