# Generated by Django 4.2 on 2024-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_xabarlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xabarlar',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterField(
            model_name='xabarlar',
            name='author',
            field=models.CharField(max_length=100, verbose_name='foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='xabarlar',
            name='author_id',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='id_raqami'),
        ),
        migrations.AlterField(
            model_name='xabarlar',
            name='text',
            field=models.TextField(verbose_name='xabar'),
        ),
    ]
