# Generated by Django 4.2 on 2024-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_xabarlar_options_alter_xabarlar_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='id_raqami')),
                ('fullname', models.CharField(max_length=150, verbose_name="to'liq_ismi")),
                ('username', models.CharField(max_length=150, verbose_name='foydalanuvchi_ismi')),
                ('phone', models.CharField(max_length=13, verbose_name='telefon_raqami')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
