# Generated by Django 5.0.6 on 2024-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='foydalanuvchi')),
                ('user_id', models.BigIntegerField(verbose_name='id_raqami')),
                ('name', models.TextField(verbose_name='mahsulot_nomi')),
                ('count', models.IntegerField(verbose_name='mahsulot_soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='mahsulot_narxi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.AlterField(
            model_name='xabarlar',
            name='author_id',
            field=models.BigIntegerField(verbose_name='id_raqami'),
        ),
    ]
