# Generated by Django 4.2 on 2024-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_savat_alter_xabarlar_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='descroption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
