# Generated by Django 5.1 on 2024-08-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_food_descroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='total_price',
            field=models.BigIntegerField(default=2, verbose_name='umumiy narxi'),
            preserve_default=False,
        ),
    ]
