# Generated by Django 5.1 on 2024-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_savat_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabarlar',
            name='username',
            field=models.CharField(default=2, max_length=150, verbose_name='foydalanuvchi_nomi'),
            preserve_default=False,
        ),
    ]
