# Generated by Django 5.1 on 2024-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_xabarlar_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='umumiy narxi'),
        ),
    ]
