# Generated by Django 5.1 on 2024-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_savat_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='sana')),
                ('user', models.CharField(max_length=100, verbose_name='foydalanuvchi')),
                ('user_id', models.BigIntegerField(verbose_name='id_raqami')),
                ('name', models.TextField(verbose_name='mahsulot_nomi')),
                ('count', models.IntegerField(verbose_name='mahsulot_soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='mahsulot_narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='umumiy narxi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, verbose_name='foydalanuvchi_nomi'),
        ),
    ]
