# Generated by Django 5.1 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_buyurtmalar_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmalar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='sana'),
        ),
    ]
