# Generated by Django 4.2 on 2024-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_buyurtmalar_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtmalar',
            name='pay',
            field=models.CharField(default=2, max_length=5, verbose_name="to'lov turi"),
            preserve_default=False,
        ),
    ]
