# Generated by Django 5.1 on 2024-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_buyurtmalar_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtmalar',
            name='status',
            field=models.CharField(default=2, max_length=10, verbose_name='buyurtma holati'),
            preserve_default=False,
        ),
    ]
