# Generated by Django 5.1 on 2024-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_karta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='card_number',
            field=models.IntegerField(verbose_name='karta_raqami'),
        ),
    ]
