# Generated by Django 5.1 on 2024-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_karta_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='card_number',
            field=models.DecimalField(decimal_places=0, max_digits=16, verbose_name='karta_raqami'),
        ),
    ]
