# Generated by Django 5.0.4 on 2024-08-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_karta_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmalar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='buyurtma_berilgan_sana'),
        ),
    ]
